### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by poiuty** [poiuty/lepus.su#3]
Алгоритм восстановления пароля.
- Пользователь вводит свой email (он же логин).
- Проходит проверку на бота (recaptcha).
- Данные попадают на php скрипт => проверяем email и recaptcha
- Генерируем hash-link для восстановления пароля.
```
hash('sha512' ,$_SERVER['HTTP_USER_AGENT'].$_SERVER['REMOTE_ADDR'].$row['passwd'].$row['login']);
```
Меняем порядок переменных - чтобы не раскрыть <a href="https://github.com/poiuty/lepus.su/issues/1" target="_blank">hash сессии</a> (переменные наоборот).
Восстановить пароль, можно только с того IP с которого был запрос на восстановление.
Восстановить пароль, можно только с того браузера с которого был запрос на восстановление.

- email и hash превратим в json и <a href="https://github.com/poiuty/lepus.su/blob/master/site/private/func.main.php#L142-L162" target="_blank">зашифруем с помощью AES-256</a> => так мы получим hash-link.
```
urlencode(lepus_crypt(json_encode($arr)))
````

- Отправим письмо с hash link на почту клиенту.
- После перехода  по ссылке => получаем $_GET['hash'].
- <a href="https://github.com/poiuty/lepus.su/blob/master/site/private/func.main.php#L24-Lundefined" target="_blank">Расшифруем данные и преобразуем их в массив</a>.
-  Снова <a href="https://github.com/poiuty/lepus.su/blob/master/site/private/func.main.php#L28" target="_blank">сгенерируем hash</a> и <a href="https://github.com/poiuty/lepus.su/blob/master/site/private/func.main.php#L29" target="_blank">сравним</a> с полученным от клиента.
- Если верно, то сгенерируем новый пароль, обновим его в базе и отправим второе письмо.

Такой способ позволяет нам не хранить временные данные.
Как только поменяется пароль =>  hash link перестанет работать.

**Comment by poiuty** [comment]
Добавил время time life url https://github.com/poiuty/lepus.su/commit/8aa4e0c5d93d4c005e3e73b32193c5e57b52dc4f 
Если с момента генерации ссылки проходит > 24 часа => выводим ошибку + редирект на главную.

**Comment by lumian** [comment]
Хотелось бы внести свои пять копеек.

"Восстановить пароль, можно только с того IP с которого был запрос на восстановление." - очень не хороший вариант. Не всегда у пользователя только один IP адрес на выходе. Постоянно с этим проблемы на не очень продуманных системах. 

Как вариант можно генерировать какой-то ключ на основе любых данных о клиенте и запихнуть его в сессию, а при переходе по линку из письма - пробовать сгенерировать ключ снова и сравнивать его с клдючем в сессии - если равны, то все окей и подтверждаем восстановление.

**Comment by poiuty** [comment]
Предполагаю, что пользователь будет восстанавливает пароль за 1~5 минут.
За это время его IP адрес скорее всего не поменяется. Пока оставляю как есть.
После релиза v0.1 => возможно пересмотрим.
